import type { AnnouncementImageKey, EditorMediaRule } from "./editor-schema";

export const MEDIA = {
  mainCoupleImage: (overrides: Partial<EditorMediaRule> = {}): EditorMediaRule => ({
    key: "main",
    type: "image",
    label: "Main Couple Image",
    description: "The main couple photograph used by this invitation.",
    descriptionKey: "media.main.description",
    descriptionLabel: "Image Description",
    descriptionPlaceholder: "Describe this photograph...",
    required: true,
    width: 768,
    height: 768,
    aspectRatio: 1,
    ...overrides,
  }),

  brideImage: (overrides: Partial<EditorMediaRule> = {}): EditorMediaRule => ({
    key: "bride",
    type: "image",
    label: "Bride Image",
    description: "Portrait photograph of the bride.",
    descriptionKey: "media.bride.description",
    descriptionLabel: "Image Description",
    descriptionPlaceholder: "Describe this photograph...",
    required: true,
    width: 600,
    height: 800,
    aspectRatio: 600 / 800,
    ...overrides,
  }),

  groomImage: (overrides: Partial<EditorMediaRule> = {}): EditorMediaRule => ({
    key: "groom",
    type: "image",
    label: "Groom Image",
    description: "Portrait photograph of the groom.",
    descriptionKey: "media.groom.description",
    descriptionLabel: "Image Description",
    descriptionPlaceholder: "Describe this photograph...",
    required: true,
    width: 600,
    height: 800,
    aspectRatio: 600 / 800,
    ...overrides,
  }),

  heroImage: (overrides: Partial<EditorMediaRule> = {}): EditorMediaRule => ({
    key: "hero",
    type: "image",
    label: "Hero Image",
    description: "The primary image displayed in the hero section.",
    descriptionKey: "media.hero.description",
    descriptionLabel: "Image Description",
    descriptionPlaceholder: "Describe this photograph...",
    required: true,
    width: 1600,
    height: 900,
    aspectRatio: 16 / 9,
    ...overrides,
  }),

  decorationImage: (
    key: AnnouncementImageKey,
    label: string,
    overrides: Partial<EditorMediaRule> = {},
  ): EditorMediaRule => ({
    key,
    type: "image",
    label,
    description: "Optional decorative image used by the invitation layout.",
    required: false,
    width: 1,
    height: 1,
    aspectRatio: 1,
    ...overrides,
  }),
};
